version: '3.8'

services:
  auth-ms:
    build: ./auth-ms
    ports:
      - "8081:8081"
    env_file:
      - ./auth-ms/.env

  profile-ms:
    build: ./profile-ms
    ports:
      - "8082:8082"
    env_file:
      - ./profile-ms/.env

  interview-ms:
    build: ./interview-ms
    ports:
      - "8083:8083"
    env_file:
      - ./interview-ms/.env

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  keycloak:
    image: quay.io/keycloak/keycloak:22.0
    command: start-dev
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8085:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      - kafka
