server:
  port: 8222

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://172.20.52.160:30080/realms/talent

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
              - "http://172.20.52.160:3000"
            allowedMethods: [GET, POST, PUT, DELETE, OPTIONS]
            allowedHeaders: "*"
            allowCredentials: true
            # if you ever use "*" origins together with allowCredentials=true,
            # switch to: allowedOriginPatterns: ["*"]

      routes:
        # ----- AUTH -----
        - id: auth-ms-route
          uri: lb://auth-ms
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - RewritePath=/api/v1/auth/(?<segment>.*),/api/auth/${segment}


            # ----- PROFILE -----
        - id: profile-ms-route
          uri: lb://profile-ms
          predicates:
            - Path=/api/v1/profile/**
          filters:
            # /api/v1/profile/**  ->  /api/v1/**
            - RewritePath=/api/v1/profile/(?<segment>.*), /api/v1/${segment}

        # ----- JOBS -----
        - id: job-ms-route
          uri: lb://job-ms
          predicates:
            - Path=/api/v1/jobs/**
          filters:

            - RewritePath=/api/v1/jobs/(?<segment>.*), /api/v1/${segment}

eureka:
  client:
    service-url:
      defaultZone: http://172.20.52.160:8761/eureka/
logging:
    level:
        org.springframework.cloud.gateway: DEBUG
        reactor.netty.http.server: DEBUG